### ISSUE TITLE
Support for transactional fixtures with Rails 6 multiple database?

### ISSUE THREAD

**Issue by steveclarke** [rspec/rspec-rails#2409]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.5.1p57
Rails version: 6.0.3.4
RSpec 3.10
  - rspec-core 3.10.0
  - rspec-expectations 3.10.0
  - rspec-mocks 3.10.0
  - rspec-rails 4.0.1
  - rspec-support 3.10.0

## Observed behaviour
I have an application that's using Rails 6 with the built-in multiple database support. My database.yml contains two databases: `primary` and `phoenix`. Snippet from `database.yml`:

``` yaml
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  encoding: utf8

phoenix_default: &phoenix_default
  <<: *default
  host: <%= ENV.fetch('DB_HOST_PHOENIX') %>
  port: <%= ENV.fetch('DB_PORT_PHOENIX') %>
  username: <%= ENV.fetch('DB_USER_PHOENIX') %>
  password: <%= ENV.fetch('DB_PASS_PHOENIX') %>

development:
  primary:
    <<: *default
    ...
  phoenix:
    <<: *phoenix_default
    database: phoenix
```

When I run tests against models using the `primary` database, the database truncates as I'm used to happening with RSpec when ` config.use_transactional_fixtures = true` is set.

When I run tests against models using the `phoenix` (second) database, the database does not truncate between each test and I get ` ActiveRecord::RecordNotUnique` errors.

## Expected behaviour

I expect the second database to be truncated between spec runs the same as when I use the primary database.

I'm wondering if multiple databases are supported out-of-the-box with RSpec 3.10 or do I need to my own truncating of the second database?
