### ISSUE TITLE
Rspec does not support cookies.delete for POST requests

### ISSUE THREAD

**Issue by halloffame** [rspec/rspec-rails#2411]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
Rails version: Rails 6.0.3.4
RSpec version: RSpec 3.10

## Observed behaviour

Cookies are not able to be deleted for POST requests. But it works fine for GET requests.

## Expected behaviour

I would expect `cookies.delete(:user_name)` to work the same in a `POST` action as it does in a `GET` action. When I test in the browser, it seems that it does indeed clear the cookie in a `POST` action, but for some reason it fails when testing in rspec. Also when I test using vanila rails test, it seems to work as expected (see sample app).

## Can you provide an example app?

https://github.com/halloffame/rsepc-rails-cookies-bug/commit/b9c6c3774d8ad55fba77e0960f58a5e9e0793e96

```ruby
# ApplicationController
class ApplicationController < ActionController::Base
  def clear_cookie
    cookies.delete(:user_name)
    head :ok
  end
end

# Routes
Rails.application.routes.draw do
  get "clear_cookie" => "application#clear_cookie"
  post "clear_cookie" => "application#clear_cookie"
end

# Rspec test
require "rails_helper"

RSpec.describe ApplicationController, :type => :controller do
  # This test passes
  it "clear cookie's value 'user_name' GET request" do
    cookies[:user_name] = "Sam"

    get :clear_cookie

    expect(cookies[:user_name]).to eq nil
  end

  # This test is failing
  it "clear cookie's value 'user_name' for POST request" do
    cookies[:user_name] = "Sam"

    post :clear_cookie

    expect(cookies[:user_name]).to eq nil
  end
end
```

```
Failures:

  1) ApplicationController clear cookie's value 'user_name' for POST request
     Failure/Error: expect(cookies[:user_name]).to eq nil
     
       expected: nil
            got: "Sam"
     
       (compared using ==)
     # ./spec/controllers/sample_spec.rb:29:in `block (2 levels) in <top (required)>'
```
