### ISSUE TITLE
Can't Set An Enum With an Integer

### ISSUE THREAD

**Issue by joelcdoyle** [rspec/rspec-rails#957]
When using the new enum feature in rails 4.1.0.rc1, rspec tests fail when attempting to set an enum with an integer vs a string. This only occurs during tests, but not when running the server.

```
Failures:

1) Api::V1::CollectionsController when creating a new collection with valid params should return 201
 Failure/Error: post :create, user_id: @user.id, collection: @collection
 ArgumentError:
   '0' is not a valid privacy_level
 # ./app/controllers/api/v1/collections_controller.rb:9:in `block in create'
 # ./app/controllers/api/v1/collections_controller.rb:8:in `each'
 # ./app/controllers/api/v1/collections_controller.rb:8:in `create'
 # ./spec/controllers/api/v1/collections_controller_spec.rb:16:in `block (3 levels) in <top (required)>'
```
